
# Set the prefix to Ctrl+A
set -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

# Set new panes to open in current directory
bind n new-window -c "#{pane_current_path}"
bind s split-window -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

# Enable mouse
set mouse on

