#!/usr/bin/ruby

begin
  require 'hirb' # sudo gem install cldwalker-hirb --source http://gems.github.com
  Hirb.enable
rescue LoadError
end

def change_log(stream)
  logger = Logger.new(stream)
  
  if defined?(ActiveRecord)
    ActiveRecord::Base.logger = logger
    ActiveRecord::Base.clear_active_connections!
  end
  
  if defined?(Mongoid)
    Mongoid.config.master.connection.instance_variable_set '@logger', logger
  end
end

def show_log
  change_log(STDOUT)
end

def hide_log
  change_log(nil)
end
