set nocompatible              " be iMproved, required
filetype off                  " required by Vundle

" Setting up Vundle - the vim plugin bundler
let VundleInstalled=1
if !isdirectory(expand("~/.vim/bundle/Vundle.vim"))
    echo "Installing Vundle.."
    echo ""
    silent !mkdir -p ~/.vim/bundle
    silent !git clone https://github.com/gmarik/Vundle.vim ~/.vim/bundle/Vundle.vim
    let VundleInstalled=0
endif

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" =============== Vundle Initialization ===============
" This loads all the plugins specified in ~/.vim/bundle.vim
" Use Vundle plugin to manage all other plugins
if filereadable(expand("~/.vim/bundle.vim"))
  source ~/.vim/bundle.vim
endif

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

if VundleInstalled == 0
    echo "Installing Bundles, please ignore key map error messages"
    echo ""
   :PluginInstall
endif

" Load ~/.vim/settings/*.vim
let vimsettings = '~/.vim/settings'
for fpath in split(globpath(vimsettings, '*.vim'), '\n')
	exe 'source' fpath
endfor
