set nocompatible              " be iMproved, required
filetype off                  " required by NeoBundle

" Setting up NeoBundle - the vim plugin bundler
let NeoBundleInstalled=1
if !isdirectory(expand("~/.vim/bundle/neobundle.vim"))
    echo "Installing NeoBundle.."
    echo ""
    silent !mkdir -p ~/.vim/bundle
    silent !git clone https://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim
    let NeoBundleInstalled=0
endif

" set the runtime path to include NeoBundle and initialize
set rtp+=~/.vim/bundle/neobundle.vim/
call neobundle#begin(expand('~/.vim/bundle/'))

" let NeoBundle manage Vundle, required
NeoBundleFetch 'Shougo/neobundle.vim'

" This loads all the plugins specified in ~/.vim/bundles.vim
source ~/.vim/bundles.vim

call neobundle#end()

filetype plugin indent on    " required

if NeoBundleInstalled == 0
    echo "Installing Bundles, please ignore key map error messages"
    echo ""
   NeoBundleInstall
endif
NeoBundleCheck

" Load ~/.vim/settings/*.vim
let vimsettings = '~/.vim/settings'
for fpath in split(globpath(vimsettings, '*.vim'), '\n')
	exe 'source' fpath
endfor
