#!/bin/sh
# Stops accidental commits to master/main/develop. https://gist.github.com/stefansundin/9059706

BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [ "$BRANCH" = "main" ] || [ "$BRANCH" = "master" ] || [ "$BRANCH" = "production" ]; then
  >&2 echo "You are on branch $BRANCH. Are you sure you want to commit to this branch?"
  >&2 echo "If so, commit with -n to bypass this pre-commit hook."
  exit 1
fi

exit 0