- clean: ['~']
- link:
    ~/.tmux.conf: tmux.conf
    ~/.gitconfig: git/gitconfig
    ~/.gitignore: git/gitignore

    # Vim
    ~/.vim: vim/
    ~/.vimrc: vim/vimrc

    # zsh
    ~/.zsh: zsh/
    ~/.zlogin: zsh/zlogin
    ~/.zlogout: zsh/zlogout
    ~/.zprezto: zsh/plugins/prezto
    ~/.zpreztorc: zsh/zpreztorc
    ~/.zprofile: zsh/zprofile
    ~/.zshenv: zsh/zshenv
    ~/.zshrc: zsh/zshrc
- shell: []
