#!/usr/bin/env bash

set -e

BASEDIR="$(pwd)"
DOTBOT_BIN="dotbot/bin/dotbot"

git submodule update --init --recursive

"${BASEDIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "config/Common.yml"

if [[ -s "config/`uname -s`.yml" ]]; then
	"${BASEDIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "config/`uname -s`.yml"
fi
