#!/bin/sh

# Install YADR
sh -c "`curl -fsSL https://raw.github.com/skwp/dotfiles/master/install.sh`"

# Symlink Dotfiles changes

# Install homebrew Cask
brew tap phinze/homebrew-cask
brew install brew-cask

#install apps
# adium arduino vlc transmit transmission spotify onepassword kindle iterm2 heroku-toolbelt google-hangouts google-chrome github evernote firefox dropbox
# brew cask install iterm2
# brew cask install spotify
# brew cask install spotify

#API_KEY="abcdef123456" brew cask install prey
