#!/bin/sh

# Install YADR
sh -c "`curl -fsSL https://raw.github.com/skwp/dotfiles/master/install.sh`"

# Symlink Dotfiles changes
rmdir $HOME/.zsh.before
ln -s $HOME/.dotfiles/zsh/before $HOME/.zsh.before
rmdir $HOME/.zsh.after
ln -s $HOME/.dotfiles/zsh/after $HOME/.zsh.after
ln -s $HOME/.dotfiles/git/config $HOME/.gitconfig.user
ln -s $HOME/.dotfiles/vim/vimrc.after $HOME/.vimrc.after

# Install Ruby
brew install rbenv
brew install ruby-build rbenv-aliases rbenv-gem-rehash rbenv-vars rbenv-ctags rbenv-default-gems
ln -s $HOME/.dotfiles/ruby/railsrc $HOME/.railsrc
ln -s $HOME/.dotfiles/ruby/default-gems /usr/local/var/rbenv/default-gems

# Install homebrew Cask
brew tap phinze/homebrew-cask
brew install brew-cask


#install apps
# adium arduino vlc transmit transmission spotify onepassword kindle iterm2 heroku-toolbelt google-hangouts google-chrome github evernote firefox dropbox
# brew cask install iterm2
# brew cask install spotify
# brew cask install spotify

#API_KEY="abcdef123456" brew cask install prey
